services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
        # networks:
        # - app-network
    depends_on:
      - frontend
      - mysql

  frontend:
    image: nginx:1.27.4
    container_name: frontend
    restart: always
    volumes:
      - ./frontend/dist:/frontend/dist
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - "7015:9090"

  mysql:
    image: mysql:8.0.40
    container_name: mysql-8
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root_sy
    ports:
      - "7014:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/my.cnf  # ✅ 修正挂载路径

networks:
  app-network:
    driver: bridge
